import type { Metadata } from "next";
import { Oswald, Josefin_Sans } from "next/font/google";
import "@/app/globals.css";

const josefinSans = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={josefinSans.className}>
        <main className="min-h-screen text-black bg-[url('/uploads/source/background/cafe-background-vintage-coffee.jpg')] bg-cover bg-no-repeat overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}
